version: "3.8"

volumes:
  mysql-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go
    env_file:
      - .env
    volumes:
      - .:/code:cached
    command: sleep infinity
    ports:
      - 8080:8080

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
